name: Keep Streamlit Alive
on:
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch: # เพิ่มบรรทัดนี้แล้ว Save/Commit ใหม่ ปุ่มกดรันเองจะขึ้นทันที
jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Streamlit App
        run: curl -s https://projectchecker-checkerform.streamlit.app/ > /dev/null
